![](https://i.ytimg.com/vi/MKxEbbKpL5Q/maxresdefault.jpg)

In this tutorial we builds an pipeline for training an pytorch model on real world dataset, Breast-Cancer-Detection. 

## Plan Of Attack 

- We will build a simple neural network
- Train it on real world dataset
- Will mimic the PyTorch worlflow
- Will have a lot of manual elements
- End result is not important

## Code Flow 
- Load the dataset
- Basic Preprocessing
- Training Process
  - Create the model
  - Forward pass
  - Loss calculation
  - Backprop
  - Parameter update
- Model Evaluation

## Import Necessary Libraries

In [1]:
import numpy as np 
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

## Load Dataset

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst  Unnamed: 32
0    842302         M        17.99  ...          0.4601                  0.11890          NaN
1    842517         M        20.57  ...          0.2750                  0.08902          NaN
2  84300903         M        19.69  ...          0.3613                  0.08758          NaN
3  84348301         M        11.42  ...          0.6638                  0.17300          NaN
4  84358402         M        20.29  ...          0.2364                  0.07678          NaN

[5 rows x 33 columns]

## Check Shape

In [3]:
df.shape

(569, 33)

## Check Missing Values

In [4]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

## Check Duplicate Rows

In [5]:
df.duplicated().sum()

0

## Drop Un-Necessary Columns

In [7]:
df.drop(['id','Unnamed: 32'],axis=1,inplace=True)

In [8]:
df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

## Train-Test-Split

In [9]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=21)

In [10]:
X_train.shape

(455, 30)

In [11]:
X_test.shape

(114, 30)

## Feature Scaling

In [12]:
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

## Label Encoding Output 

In [13]:
y_train

224    B
252    M
82     M
88     B
169    B
      ..
419    B
120    B
368    M
48     B
207    M
Name: diagnosis, Length: 455, dtype: object

In [14]:
le = LabelEncoder()

y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [18]:
y_test

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1])

## Numpy Arrays to PyTorch Tensor

In [19]:
X_train_tensor = torch.from_numpy(X_train_sc)
X_test_tensor = torch.from_numpy(X_test_sc)

In [25]:
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)
# print(y_train_tensor,y_test_tensor)

In [20]:
X_train_tensor

tensor([[-0.2605, -0.5458, -0.3234,  ..., -0.3044, -0.6542, -0.4403],
        [ 1.5758,  0.1002,  1.5788,  ...,  2.0245, -0.2604,  2.4445],
        [ 3.1365,  1.2745,  3.2606,  ...,  2.5692, -0.8988,  1.1173],
        ...,
        [ 2.1387, -0.4928,  1.9993,  ...,  0.9850, -0.6477, -1.0494],
        [-0.6073, -1.0972, -0.5918,  ..., -0.7780, -0.2637, -0.0745],
        [ 0.8026,  0.2017,  0.7132,  ..., -0.1104,  0.5918, -1.0629]],
       dtype=torch.float64)

In [21]:
X_test_tensor

tensor([[-0.9456,  0.4832, -0.9846,  ..., -1.7688, -0.7319, -0.9966],
        [ 0.2170, -0.1421,  0.2244,  ..., -0.4970, -0.0935,  0.4202],
        [ 1.7350, -1.1641,  1.7602,  ...,  0.6900, -0.8842, -0.4106],
        ...,
        [-0.6017, -1.3718, -0.6004,  ..., -0.6502, -0.2086, -0.2089],
        [-1.5679, -1.1387, -1.5654,  ..., -1.7688, -0.5148, -0.3189],
        [ 0.3620, -1.7294,  0.4164,  ...,  0.9956,  0.4962,  0.8961]],
       dtype=torch.float64)

## Define Model

In [28]:
class MyModel():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred 

    def loss_function(self,y_pred,y):
        ## clamp prediction to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

        # calculate loss 
        loss = - (y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()
        return loss
        

In [29]:
## define learning rate and epochs 
learning_rate = 0.1
epochs = 25

In [31]:
## create model

model = MyModel(X_train_tensor)

for epoch in range(epochs):
    ## forward pass
    y_pred = model.forward(X_train_tensor)
    ## loss function
    loss = model.loss_function(y_pred,y_train_tensor)
    ## backward pass
    loss.backward()
    ## parameter update 
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    ## zero gradient 
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')
        

Epoch: 1, Loss: 3.7114025878065
Epoch: 2, Loss: 3.5876286100427626
Epoch: 3, Loss: 3.4598653337888807
Epoch: 4, Loss: 3.3243590286831264
Epoch: 5, Loss: 3.185792317436818
Epoch: 6, Loss: 3.0433185554277813
Epoch: 7, Loss: 2.8911685512162917
Epoch: 8, Loss: 2.7367579244426925
Epoch: 9, Loss: 2.5767485718670056
Epoch: 10, Loss: 2.415778792810994
Epoch: 11, Loss: 2.2525793394060436
Epoch: 12, Loss: 2.0904321920999482
Epoch: 13, Loss: 1.9342458756034022
Epoch: 14, Loss: 1.7825303869036444
Epoch: 15, Loss: 1.640246028053891
Epoch: 16, Loss: 1.5049443491238101
Epoch: 17, Loss: 1.372819006291432
Epoch: 18, Loss: 1.2554214147485698
Epoch: 19, Loss: 1.1541090436993995
Epoch: 20, Loss: 1.0696149389169005
Epoch: 21, Loss: 1.0015699741086674
Epoch: 22, Loss: 0.948351604018355
Epoch: 23, Loss: 0.9074400165131351
Epoch: 24, Loss: 0.8760442243822558
Epoch: 25, Loss: 0.8516319692893628


In [35]:
model.weights.shape

torch.Size([30, 1])

In [34]:
model.bias

tensor([-0.1219], dtype=torch.float64, requires_grad=True)

## Evaluation

In [36]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred>0.9).float()
    accuracy = (y_pred==y_test_tensor).float().mean()
    print(f'Accuarcy: {accuracy.item()}')

Accuarcy: 0.638504147529602


![](https://i.ytimg.com/vi/CAgWNxlmYsc/hqdefault.jpg)

## Plan Of Action 
- The nn module
- The torch.optim module
- Improvement Existing Model

## Improvements 
- Buiding Neural Network using nn module
- Using built in activation function
- Using built-in loss function
- Using built-in optimizer

# The nn module

### **The torch.nn module in PyTorch is a core library that provides a wide array of classes and functions designed to help developers build neural networks efficiently and effectively.**
### **It abstarcts the complexity of creating and training neural networks by offering pre-builts layers, loss functions, activations or other utilities, enabling you to focus on designing and experimenting with model architectures.**

# Key Components of torch.nn

1. Modules (Layers):
   - **nn.module:** The base class for all neural network modules. Your custom models and layers subclass in this class.
   - **Common Layers:** Includes layers like **nn.Liner (fully connected layer), nn.Conv2d (convolution layer), nn.LSTM (recurrent layer)** and many others.

2. Actiavtion Functions
   - Functions like **nn.ReLu**, **nn.Sigmoid**, **nn.Tanh** introduces non-linearility to the model, allowing it to learn complex patterns.

3. Loss Functions:
   - Provides Loss functions such as **nn.CrossEntropyLoss, nn.MSELoss, nn.NLLLoss** to quantify the difference between the model's predictions and the actual targets.

4. Container Modules:
   - **nn.Sequential:** A sequential container to stack layers in order.

5. Regularization and Dropout:
   - Layers like **nn.Dropout and nn.BatchNorm2d** help prevent overfitting and improve the model's ability to generalize to new data.

## The torch.optim module 

### **torch.optim is a module in PyTorch that provides a variety of optimization algorithms used to update the parameters of your model during training.**

### **It includes common optimizers like Stochastic Gradient Descent (SGD), Adam, RMSprop, and more.**

### **It handles weight updates efficiently, including additional features like learning rate scheduling and weight decay (regularization).**

### **The model.parameter() method in PyTorch retrieves an iterator over all the trainable parameters (weights and biases) in a model. The optimizer uses these parameters to compute gradients and update them during training.**

## Improves Code -- Existing Model 

## create model

model = MyModel(X_train_tensor)

for epoch in range(epochs):
    ## forward pass
    y_pred = model.forward(X_train_tensor)
    ## loss function
    loss = model.loss_function(y_pred,y_train_tensor)
    ## backward pass
    loss.backward()
    ## parameter update 
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    ## zero gradient 
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')
        

## Improvements -- Replace with PyTorch nn module

In [57]:
import torch 
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            ## input layer 
            nn.Linear(num_features,3),
            #applied relu
            nn.ReLU(),
            # output layer
            nn.Linear(3,1),
            ## applied sigmoid
            nn.Sigmoid()
        )

    def forward(self,features):
        out = self.network(features)
        return out

# Make sure both tensors are of type float32
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float()


model = MyModel(X_train_tensor.shape[1])

## define optimizer 
optimizer = torch.optim.SGD(model.parameters(),lr=0.1)

## define loop 
for epoch in range(25):
    y_pred = model(X_train_tensor)
    loss_function = nn.BCELoss()
    loss = loss_function(y_pred,y_train_tensor.view(-1,1))

    ## clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    ## parameter update
    optimizer.step()

    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

  

Epoch: 1, Loss: 0.6869089603424072
Epoch: 2, Loss: 0.667261004447937
Epoch: 3, Loss: 0.6488147377967834
Epoch: 4, Loss: 0.6306271553039551
Epoch: 5, Loss: 0.6134985089302063
Epoch: 6, Loss: 0.5966671705245972
Epoch: 7, Loss: 0.5805893540382385
Epoch: 8, Loss: 0.565207302570343
Epoch: 9, Loss: 0.5506453514099121
Epoch: 10, Loss: 0.5369421243667603
Epoch: 11, Loss: 0.523980438709259
Epoch: 12, Loss: 0.5119075775146484
Epoch: 13, Loss: 0.5006181597709656
Epoch: 14, Loss: 0.4901822507381439
Epoch: 15, Loss: 0.4805448055267334
Epoch: 16, Loss: 0.47151970863342285
Epoch: 17, Loss: 0.4631381332874298
Epoch: 18, Loss: 0.45528191328048706
Epoch: 19, Loss: 0.44784975051879883
Epoch: 20, Loss: 0.4408469796180725
Epoch: 21, Loss: 0.4342362582683563
Epoch: 22, Loss: 0.42795196175575256
Epoch: 23, Loss: 0.42196890711784363
Epoch: 24, Loss: 0.41629114747047424
Epoch: 25, Loss: 0.4109046161174774


## Model Evaluation

In [58]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred>0.9).float()
    accuracy = (y_pred==y_test_tensor).float().mean()
    print(f'Accuarcy: {accuracy.item()}')

Accuarcy: 0.6578947305679321


In [45]:
!pip install torchinfo

DEPRECATION: Loading egg at c:\users\rajsi\anaconda3\lib\site-packages\mask_rcnn-2.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330


## Show Model Summary

In [60]:
from torchinfo import summary

summary(model,input_size=(X_train_tensor.shape))

Layer (type:depth-idx)                   Output Shape              Param #
MyModel                                  [455, 1]                  --
├─Sequential: 1-1                        [455, 1]                  --
│    └─Linear: 2-1                       [455, 3]                  93
│    └─ReLU: 2-2                         [455, 3]                  --
│    └─Linear: 2-3                       [455, 1]                  4
│    └─Sigmoid: 2-4                      [455, 1]                  --
Total params: 97
Trainable params: 97
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.04
Input size (MB): 0.05
Forward/backward pass size (MB): 0.01
Params size (MB): 0.00
Estimated Total Size (MB): 0.07