<a href="https://colab.research.google.com/github/datamind321/pytorch-tutorial/blob/main/Pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![](https://i.ytimg.com/vi/MKxEbbKpL5Q/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLA_pvVrpRXVtQl7sRN2B8qhkSC19A)

## Plan of Attack

- We will build a simple neural network
- Train it on real-world dataset
- Will mimic the PyTorch workflow
- Will have a lot of manual elements
- End result is not important

## Code Flow
- Load Dataset
- Basic Preprocessing
  - train_test_split
  - scaling
  - label-encoding
- Training Process
 - Create the model
 - forward pass
 - loss calculation
 - Backprop
 - Parameter update

- Model Evaluation

## Code Demo


In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# Load Dataset

In [ ]:
df = pd.read_csv('/content/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

## drop un-necessary columns

In [ ]:
df.drop(['id','Unnamed: 32'],axis=1,inplace=True)

##  Train Test Split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=21)

In [ ]:
y_train

224    B
252    M
82     M
88     B
169    B
      ..
419    B
120    B
368    M
48     B
207    M
Name: diagnosis, Length: 455, dtype: object

## Scaling

In [ ]:
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_test

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1])

## Numpy array to PyTorch Tensor

In [ ]:
X_train_tensor = torch.from_numpy(X_train_sc)
X_test_tensor = torch.from_numpy(X_test_sc)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor

tensor([[-0.2605, -0.5458, -0.3234,  ..., -0.3044, -0.6542, -0.4403],
        [ 1.5758,  0.1002,  1.5788,  ...,  2.0245, -0.2604,  2.4445],
        [ 3.1365,  1.2745,  3.2606,  ...,  2.5692, -0.8988,  1.1173],
        ...,
        [ 2.1387, -0.4928,  1.9993,  ...,  0.9850, -0.6477, -1.0494],
        [-0.6073, -1.0972, -0.5918,  ..., -0.7780, -0.2637, -0.0745],
        [ 0.8026,  0.2017,  0.7132,  ..., -0.1104,  0.5918, -1.0629]],
       dtype=torch.float64)

In [ ]:
y_train_tensor

tensor([0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
        1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
        1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
X_test_tensor.shape

torch.Size([114, 30])

## Define Model

In [ ]:
class MyNNModel():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def Loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    # calculate loss
    loss = -(y * torch.log(y_pred) + (1 - y)*torch.log(1-y_pred)).mean()
    return loss


In [ ]:
learning_rate=0.1
epochs=30

In [ ]:
# create model
model = MyNNModel(X_train_tensor)

# forward pass

for epoch in range(epochs):
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.Loss_function(y_pred,y_train_tensor)
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

  # backward pass
  loss.backward()

  #parameter update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  ## zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()




Epoch: 1, Loss: 3.697955805487685
Epoch: 2, Loss: 3.5679242478360664
Epoch: 3, Loss: 3.436595666418294
Epoch: 4, Loss: 3.304565988969064
Epoch: 5, Loss: 3.1694236488790044
Epoch: 6, Loss: 3.0285668082237134
Epoch: 7, Loss: 2.8824572373010398
Epoch: 8, Loss: 2.7338943019236814
Epoch: 9, Loss: 2.579885303293205
Epoch: 10, Loss: 2.423426492855431
Epoch: 11, Loss: 2.2685013398432297
Epoch: 12, Loss: 2.115625726921789
Epoch: 13, Loss: 1.960908300853878
Epoch: 14, Loss: 1.8070241222676882
Epoch: 15, Loss: 1.6612271620148347
Epoch: 16, Loss: 1.5264175426299675
Epoch: 17, Loss: 1.4019899279340453
Epoch: 18, Loss: 1.2855386535360114
Epoch: 19, Loss: 1.184506582877498
Epoch: 20, Loss: 1.0992752443381322
Epoch: 21, Loss: 1.0294738074851515
Epoch: 22, Loss: 0.9739150233764755
Epoch: 23, Loss: 0.930598964281776
Epoch: 24, Loss: 0.897008791174308
Epoch: 25, Loss: 0.8706951797468614
Epoch: 26, Loss: 0.8496733303040929
Epoch: 27, Loss: 0.8324824465117837
Epoch: 28, Loss: 0.8180933509353231
Epoch: 29, 

In [ ]:
model.weights

tensor([[ 0.5604],
        [ 0.0151],
        [ 0.1402],
        [-0.1484],
        [-0.0707],
        [-0.2584],
        [ 0.1907],
        [-0.0552],
        [ 0.3337],
        [ 0.3144],
        [-0.2442],
        [ 0.2425],
        [ 0.0050],
        [-0.1700],
        [ 0.4755],
        [ 0.3845],
        [ 0.2381],
        [-0.3797],
        [ 0.2889],
        [-0.4408],
        [-0.2048],
        [ 0.3609],
        [-0.1293],
        [ 0.4299],
        [-0.3319],
        [-0.0437],
        [-0.4390],
        [-0.0519],
        [ 0.2061],
        [ 0.2148]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.1579], dtype=torch.float64, requires_grad=True)

## model evaluation

In [ ]:
with torch.no_grad():
  y_pred = model.forward(X_train_tensor)
  y_pred = (y_pred>0.5).float()
  accuracy = (y_pred == y_train_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5292211174964905
