![](https://i.ytimg.com/vi/_R-mvKBD5U8/maxresdefault.jpg)

## **What is Tensor ??**

### **Tensor is a fundamental building block of Pytorch, and it is basically the same as a Numpy array.**

### **Tensor is a specialized multi-dimensional array designed for mathematical and computational efficiency.**

### **It is mostly used for converting Images, Audio into a mathematical form used for processing, as computers don’t understand images but standard numbers. Hence, it is important to convert images into numerical forms.**

## **What is the types of Tensor ??**

- Scaler is a 0-dimensional Vector
- Vector is a 1-dimensional Vector
- Matrices are 2-dimensional Vector
- Tensors are generalized N-dimensional Tensors

1. **Scalars: 0-Dimensional tensors (a single number)**

  - Represents as a single value, often used for simple matrics or constants.
    - **Example:**
      - **Loss value**: After a forward pass, the loss function computes a single scalar value indicating the difference between actual and predicted outputs.
      - **Example:** 5.0 or -3.14


2. **Vectors: 1-Dimensional tensors (a list of numbers)**
   - Represents a sequence or collection of values.
   - **Example:**
      - **Feature vector**: In natural language processing, each word in a sentence may be represents as a 1D vector using embeddings.
      - **Example:**[0.12,-0.84,0.23] (a word embedding vector from a pre-trained model like word2vec or Glove).

3. **Matrices: 2-Dimensional tensors (a 2d grid of numbers)**
  - Represents tabular or grid-like data
  - **Example:**
     - **Grayscale images**: A grayscale image can be represented as a 2d tensor, where each entry corresponds to the pixel intensity.
     - **Example:** [[0,255,128],[34,90,128]]

4. **3D Tensors: Coloured Images**
   - Adds a third dimension, often used for stacking data.
   - **Example:**
      - **RGB Images:** A single RGB image is represented as a 3d tensor (width*height*channels)
      - **Examples:**
         - RGB Image (eg. 256x256): Shape [256,256,3]
5. **4D Tensor: Batches of RGB Images**
   - Adds the batch size as an additional dimension to 3d data
   - **Example:**
      - **Batches of RGB Images:** A dataset coloured images is represented as a 4D tensor (batch size x width x height x channels)
      - **Example:** A batch of 32 images, each of size is 128x128 with 3 colour channels (RGB), would have shape [32,128,128,3]

6. **5D Tensors: Video Data**
   - Adds a time dimension for data that changes over time (eg video frame)
   - **Example:**
      - **Video clips:** Represented as a sequence of frames, where each frame is an RGB image.
      - **Example:** A batch of 10n video clips, each with 16 frames of size 64x64 and 3 channels (RGB), would have shape [10,16,64,64,3]


## **Why are Tensors Useful ??**

1. **Mathematical Operations**
   - Tensors Enable efficient mathematical computations (addition,multiplication, dot product, etc) necessary for neural network operations.

2. **Representation of Real-World Data**
   - Data like images, audio, text can be represented tensors:
      - **Images:** Represented as a 3D tensors (width x height x channels)
      - **Text:** Tokenized and represented as 2D or 3D tensors (sequence length x embedding size)

3. **Efficient Computation**
   - Tensors are optimized for hardware acceleration, allowing computation on GPUs orf TPUs, which are crucial fpr training deep learning models.


## **Where are Tensors are used in Deep Learning ?**

1. **Data Storage**
   - Training data (images,text etc.) is stored in tensors.
2. **Weights and Biases**
    - The learnable parameter of a neural network (weights and biases) are stored in tensors.

3. **Matrix Operations**
   - Neural networks involve operations like matrix multiplication, dot products, and broadcasting-all performed using tensors.

4. **Traing Process**
   - During forward passes, tensors flow through the network.
   - Gradients, represented as tensors, are calculated during the backward pass.

## Practical Code Implementation

In [104]:
import torch
print(torch.__version__)

2.5.1+cu121


## Check GPU is available or not ??

In [105]:
if torch.cuda.is_available():
    print('GPU is available!')
    print(f'Using GPU: {torch.cuda.get_device_name()}')
else:
    print('GPU is not available!')

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [106]:
import torch

# create an empty tensor
a = torch.empty(2,3)
print(a)
## check type
print(type(a))

tensor([[-7.9633e-32,  4.3687e-41, -3.4137e+13],
        [ 3.1128e-41,  0.0000e+00,  0.0000e+00]])
<class 'torch.Tensor'>


In [107]:
## using zeros to create tensor
torch.zeros(2,3)
## used to intilized weights and biases

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [108]:
## using ones to creates tensor
torch.ones(2,3)
## intilize weights (1) and biases (0)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [109]:
## using rand to create tensor
torch.rand(2,3)
## randomly assign weights and biases
## used weight initialization techniques

tensor([[0.7158, 0.0702, 0.4443],
        [0.6302, 0.6179, 0.1797]])

In [110]:
## manual_seed : use to same random numbers between two users
## user 1
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [111]:
## user 2
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [112]:
## using tensor function
## 0d tensor: scaler
t0 = torch.tensor(1)
## 1d tensor: vector or array
t1 = torch.tensor([1,2,3])
## 2d tensor: matries
t2 = torch.tensor([[1,2,3],[4,5,6]])

print(t0)
print(t1)
print(t2)

## check shape
print('--- Check shapes of tensors -----')
print(t0.shape)
print(t1.shape)
print(t2.shape)


tensor(1)
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
--- Check shapes of tensors -----
torch.Size([])
torch.Size([3])
torch.Size([2, 3])


In [113]:
## using arange function - similar to np.arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [114]:
## using linspace similar to np.linspace
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [115]:
## using eye function : identity tensors
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [116]:
## using full function
torch.full((3,3),5)
## torch.full((shape),value)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [117]:
## empty_like function used to create an another tensor similar shape of one.

t1 = torch.tensor([[1,2,3],[4,5,6]])
print(t1)

## suppose that, we want to create an empty tensor similar to t1
t2 = torch.empty_like(t1)
print(t2)

t3 = torch.zeros_like(t2)
print(t3)


t4 = torch.ones_like(t2)
print(t4)

## raise error : because it's generate float values but t4 is integer type
## solution : assign dtype
t5 = torch.rand_like(t4,dtype=torch.float32)
print(t5)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[133902246002064, 133902246002064,  95411993370368],
        [ 95411993996560,               0,  95411993362208]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


In [118]:
## check data type any tensor
print(t1.dtype)

torch.int64


In [119]:
## assign data type
tns = torch.tensor([1.0,2.0,3.0],dtype=torch.int32)
tns

tensor([1, 2, 3], dtype=torch.int32)

In [120]:
t1 = torch.tensor([1,2,3],dtype=torch.float64)
print(t1)

t2 = torch.rand_like(t1)
print(t2)

## solve previous error : assign dtype: float in t1

tensor([1., 2., 3.], dtype=torch.float64)
tensor([0.6941, 0.3464, 0.9751], dtype=torch.float64)


In [121]:
print(t1.dtype)
## change datatype t1
t1 = t1.to(torch.int32)
print(t1.dtype)

torch.float64
torch.int32


## Mathematical Operation on Tensor

### Scaler Operation

In [122]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [123]:
## addition
x+1

tensor([[1.2239, 1.3023],
        [1.1784, 1.8238]])

In [124]:
## substraction
x-1

tensor([[-0.7761, -0.6977],
        [-0.8216, -0.1762]])

In [125]:
## multiplication
x*2

tensor([[0.4478, 0.6047],
        [0.3568, 1.6477]])

In [126]:
## division
x/2

tensor([[0.1119, 0.1512],
        [0.0892, 0.4119]])

In [127]:
## int divison
(x*100)//3

tensor([[ 7., 10.],
        [ 5., 27.]])

In [128]:
## mod
((x*100)//3)%2

tensor([[1., 0.],
        [1., 1.]])

In [129]:
## power
x**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

## Elementwise Operation

In [130]:
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a)
print(b)

tensor([[0.5557, 0.9770],
        [0.4440, 0.9478]])
tensor([[0.7445, 0.4892],
        [0.2426, 0.7003]])


In [131]:
## addition
print(a+b)

tensor([[1.3002, 1.4662],
        [0.6866, 1.6482]])


In [132]:
## substraction
print(a-b)

tensor([[-0.1887,  0.4878],
        [ 0.2015,  0.2475]])


In [133]:
## multiplication
print(a*b)

tensor([[0.4137, 0.4780],
        [0.1077, 0.6638]])


In [134]:
## divison
print(a/b)

tensor([[0.7465, 1.9972],
        [1.8306, 1.3534]])


In [135]:
## power
print(a**b)

tensor([[0.6457, 0.9887],
        [0.8212, 0.9632]])


In [136]:
## mod
print(a%b)

tensor([[0.5557, 0.4878],
        [0.2015, 0.2475]])


In [137]:
## abs
c = torch.tensor([1,-2,3,-4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [138]:
## negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [139]:
## round
d = torch.tensor([1.9,2.3,3.7,4.4])
torch.round(d)

tensor([2., 2., 4., 4.])

In [140]:
## ceil : next integer
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [141]:
## floor : previous integer
torch.floor(d)

tensor([1., 2., 3., 4.])

In [142]:
## clamp : range betwwen 2 to 3
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction Operation

In [143]:
a = torch.randint(size=(2,3),low=0,high=10)
a

tensor([[7, 0, 0],
        [9, 5, 7]])

In [144]:
## sum
torch.sum(a)

tensor(28)

In [145]:
## sum along column - column wise sum
torch.sum(a,dim=0)

tensor([16,  5,  7])

In [146]:
# sum along row - row wise sum
torch.sum(a,dim=1)

tensor([ 7, 21])

In [147]:
## mean
torch.mean(a,dtype=torch.float32)

tensor(4.6667)

In [148]:
## mean - column wise
torch.mean(a,dtype=torch.float32,dim=0)

tensor([8.0000, 2.5000, 3.5000])

In [149]:
## mean - row wise
torch.mean(a,dtype=torch.float32,dim=1)

tensor([2.3333, 7.0000])

In [150]:
## standard deviation
torch.median(a)

tensor(5)

In [151]:
## min and max
print(torch.min(a))
print(torch.max(a))

tensor(0)
tensor(9)


In [152]:
print(a)
torch.prod(a)
## product is 0 because one element is 0

tensor([[7, 0, 0],
        [9, 5, 7]])


tensor(0)

In [153]:
## argmax
print(a)
torch.argmax(a)
## tell the max element position which is 1

tensor([[7, 0, 0],
        [9, 5, 7]])


tensor(3)

In [154]:
## argmin
print(a)
torch.argmin(a)
## tell the min element position which is 2

tensor([[7, 0, 0],
        [9, 5, 7]])


tensor(1)

## Matrix Operation

In [155]:
t1 = torch.randint(size=(3,2),low=0,high=3)
t2 = torch.randint(size=(2,3),low=0,high=3)

t3 = torch.matmul(t1,t2)
print(t3)

tensor([[0, 0, 0],
        [0, 2, 0],
        [0, 2, 0]])


In [156]:
## dot product
a = torch.tensor([1,2])
b = torch.tensor([3,4])

torch.dot(a,b)

tensor(11)

In [157]:
## transpose

t1 = torch.tensor([[3,7,8],[7,9,9],[5,6,7]],dtype=torch.float32)
print(t1)

torch.transpose(t1,0,1)

tensor([[3., 7., 8.],
        [7., 9., 9.],
        [5., 6., 7.]])


tensor([[3., 7., 5.],
        [7., 9., 6.],
        [8., 9., 7.]])

In [158]:
## determinant
torch.det(t1)

tensor(-25.)

In [159]:
## inverse
torch.inverse(t1)

tensor([[-0.3600,  0.0400,  0.3600],
        [ 0.1600,  0.7600, -1.1600],
        [ 0.1200, -0.6800,  0.8800]])

## Comparison Operation

In [160]:
t1 = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
t2 = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

print(t1)
print(t2)

tensor([[8., 9., 7.],
        [9., 2., 6.]])
tensor([[7., 7., 8.],
        [3., 6., 1.]])


In [161]:
## greater than
print(t1 > t2)
## less than
print(t1 < t2)
## qual to
print(t1==t2)
## not equal to
print(t1!=t2)

tensor([[ True,  True, False],
        [ True, False,  True]])
tensor([[False, False,  True],
        [False,  True, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


## Special Function

In [162]:
print(t1)

## log function
torch.log(t1)

tensor([[8., 9., 7.],
        [9., 2., 6.]])


tensor([[2.0794, 2.1972, 1.9459],
        [2.1972, 0.6931, 1.7918]])

In [163]:
## exp
torch.exp(t1)

tensor([[2.9810e+03, 8.1031e+03, 1.0966e+03],
        [8.1031e+03, 7.3891e+00, 4.0343e+02]])

In [164]:
## square root
torch.sqrt(t1)

tensor([[2.8284, 3.0000, 2.6458],
        [3.0000, 1.4142, 2.4495]])

In [165]:
## sigmoid
torch.sigmoid(t1)

tensor([[0.9997, 0.9999, 0.9991],
        [0.9999, 0.8808, 0.9975]])

In [166]:
## softmax p column wise
torch.softmax(t1,dim=0)

tensor([[2.6894e-01, 9.9909e-01, 7.3106e-01],
        [7.3106e-01, 9.1105e-04, 2.6894e-01]])

In [167]:
## relu
torch.relu(t1)

tensor([[8., 9., 7.],
        [9., 2., 6.]])

## Inplace Operation

In [168]:
m = torch.rand(2,3)
n = torch.randn(2,3)

print(m)
print(n)

tensor([[0.3039, 0.6726, 0.5740],
        [0.9233, 0.9178, 0.7590]])
tensor([[ 0.2903,  1.5309, -2.1057],
        [-0.8782,  0.1341, -1.9036]])


In [169]:
m+n
## it allocates new memories for this operation

tensor([[ 0.5942,  2.2035, -1.5317],
        [ 0.0451,  1.0519, -1.1445]])

In [170]:
m.add_(n)

tensor([[ 0.5942,  2.2035, -1.5317],
        [ 0.0451,  1.0519, -1.1445]])

In [171]:
m
# changes in m not creates in new memory

tensor([[ 0.5942,  2.2035, -1.5317],
        [ 0.0451,  1.0519, -1.1445]])

In [172]:
n ## same as previous

tensor([[ 0.2903,  1.5309, -2.1057],
        [-0.8782,  0.1341, -1.9036]])

In [173]:
m.relu_()

tensor([[0.5942, 2.2035, 0.0000],
        [0.0451, 1.0519, 0.0000]])

In [174]:
m

tensor([[0.5942, 2.2035, 0.0000],
        [0.0451, 1.0519, 0.0000]])

## Copying an tensor

In [175]:
a = torch.rand(2,3)
a

tensor([[0.6868, 0.4920, 0.0748],
        [0.9605, 0.3271, 0.0103]])

In [176]:
## first method
b = a
b

## problem : if i am changes on a ,changes also b

tensor([[0.6868, 0.4920, 0.0748],
        [0.9605, 0.3271, 0.0103]])

In [177]:
## example
a[0][0] = 0
a

tensor([[0.0000, 0.4920, 0.0748],
        [0.9605, 0.3271, 0.0103]])

In [178]:
b

tensor([[0.0000, 0.4920, 0.0748],
        [0.9605, 0.3271, 0.0103]])

In [179]:
## b mein bhi change ho gaya , which is not desirable

In [180]:
print(id(a))
print(id(b))

133899286741936
133899286741936


In [181]:
## second method
a = torch.rand(3,2)
b = a.clone()
print(a)
print(b)

tensor([[0.9516, 0.2855],
        [0.2324, 0.9141],
        [0.7668, 0.1659]])
tensor([[0.9516, 0.2855],
        [0.2324, 0.9141],
        [0.7668, 0.1659]])


In [182]:
a[0][0] = 0
a

tensor([[0.0000, 0.2855],
        [0.2324, 0.9141],
        [0.7668, 0.1659]])

In [183]:
b

tensor([[0.9516, 0.2855],
        [0.2324, 0.9141],
        [0.7668, 0.1659]])

In [184]:
## b mein changes mnahi hue that's good

In [185]:
print(id(a))
print(id(b))

133899286646192
133899286656272


## Tensor Operation On GPU

In [186]:
torch.cuda.is_available()

True

In [187]:
device = torch.device('cuda')

In [188]:
device

device(type='cuda')

In [189]:
## creating an new tensor on GPU
torch.rand(2,3,device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [190]:
## moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.4393, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])

In [191]:
b = a.to(device)
b
## b mein ab jo bhi operation perform hoge woh gpu mein hoge

tensor([[0.4393, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]], device='cuda:0')

## Comparison Time Operation perform Between CPU Vs GPU

In [192]:
import time

## define the size of the matrices
size = 10000

## craete random matrices on CPU
matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)


## measure on cpu

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time() - start_time

print(f'time on cpu: {cpu_time:.4f} seconds')

##Move matrix to GPU

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

## measure time on GPU

start_time = time.time()
result_cpu = torch.matmul(matrix_gpu1,matrix_gpu2)
gpu_time = time.time() - start_time

print(f'time on gpu: {gpu_time:.4f} seconds')


time on cpu: 25.6340 seconds
time on gpu: 0.0009 seconds


## Reshaping Tensor

In [193]:
x = torch.ones(4,4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [194]:
## reshape
x.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [195]:
## flatten
torch.flatten(x)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [196]:
## permute
c = torch.rand(2,3,4)
c

tensor([[[0.5752, 0.8881, 0.7989, 0.9514],
         [0.0141, 0.8903, 0.1649, 0.3162],
         [0.1331, 0.6763, 0.4254, 0.2375]],

        [[0.5430, 0.1174, 0.6532, 0.5115],
         [0.3094, 0.7907, 0.7351, 0.2693],
         [0.8009, 0.5839, 0.0061, 0.4671]]])

In [197]:
c.permute(2,0,1)
## now shape is (4,2,3)  -- original is (2,3,4)

tensor([[[0.5752, 0.0141, 0.1331],
         [0.5430, 0.3094, 0.8009]],

        [[0.8881, 0.8903, 0.6763],
         [0.1174, 0.7907, 0.5839]],

        [[0.7989, 0.1649, 0.4254],
         [0.6532, 0.7351, 0.0061]],

        [[0.9514, 0.3162, 0.2375],
         [0.5115, 0.2693, 0.4671]]])

In [198]:
## unsqueeze
## image size
img = torch.rand(226,226,3)

In [199]:
img.unsqueeze(0).shape
## single batch

torch.Size([1, 226, 226, 3])

In [200]:
## squueze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy & PyTorch

In [201]:
import numpy as np

In [202]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [203]:
type(a)

torch.Tensor

In [204]:
b = a.numpy()
## covert tensor to numpy array
print(type(b))

<class 'numpy.ndarray'>


In [205]:
c = np.array([1,2,3])
print(type(c))

<class 'numpy.ndarray'>


In [206]:
## convert numpy array to tensor
torch.from_numpy(c)

tensor([1, 2, 3])